// 📁 PATH: src/components/admin/customers/_dummyData.js
// ⚠️  NEW FILE

const now = Date.now();
const d  = (days)  => new Date(now - 86400000 * days).toISOString();
const ds = (days)  => new Date(now - 86400000 * days);

export const DUMMY_CUSTOMERS = [
  {
    _id: 'c001', firstName: 'Sarah', lastName: 'Johnson',
    email: 'sarah.johnson@email.com', phone: '+1 (212) 555-0101',
    role: 'buyer', isActive: true, emailVerified: true, isBanned: false,
    totalOrders: 24, totalSpent: 3842.50, avgOrderValue: 160.1, lastOrderAt: d(1),
    createdAt: d(420), addresses: [{ label: 'Home', street: '123 Maple Ave', city: 'New York', state: 'NY', zip: '10001', country: 'US', isDefault: true }],
    savedCards: 2, wishlistCount: 14, reviewCount: 9,
    tags: ['VIP', 'Repeat Buyer', 'High LTV'],
    notes: [{ _id: 'n1', text: 'Prefers email communication. Loyal since 2022. Never returned an item.', createdAt: d(30), author: 'Admin' }],
    ltv: 5200, riskScore: 'low',
  },
  {
    _id: 'c002', firstName: 'Marcus', lastName: 'Thompson',
    email: 'mthompson@company.com', phone: '+1 (415) 555-0202',
    role: 'buyer', isActive: true, emailVerified: true, isBanned: false,
    totalOrders: 11, totalSpent: 1280.40, avgOrderValue: 116.4, lastOrderAt: d(4),
    createdAt: d(210), addresses: [{ label: 'Office', street: '88 Market St', city: 'San Francisco', state: 'CA', zip: '94105', country: 'US', isDefault: true }],
    savedCards: 1, wishlistCount: 7, reviewCount: 4,
    tags: ['Active', 'B2B'],
    notes: [],
    ltv: 1800, riskScore: 'low',
  },
  {
    _id: 'c003', firstName: 'Priya', lastName: 'Sharma',
    email: 'priya.s@startup.io', phone: '+1 (650) 555-0303',
    role: 'buyer', isActive: true, emailVerified: true, isBanned: false,
    totalOrders: 31, totalSpent: 5610.80, avgOrderValue: 181.0, lastOrderAt: d(0),
    createdAt: d(730), addresses: [{ label: 'Home', street: '42 University Ave', city: 'Palo Alto', state: 'CA', zip: '94301', country: 'US', isDefault: true }, { label: 'Work', street: '1 Hacker Way', city: 'Menlo Park', state: 'CA', zip: '94025', country: 'US', isDefault: false }],
    savedCards: 3, wishlistCount: 22, reviewCount: 15,
    tags: ['VIP', 'Top Spender', 'Repeat Buyer'],
    notes: [{ _id: 'n2', text: 'Champion customer. Send personalized quarterly gifts. CC on VIP newsletter.', createdAt: d(14), author: 'Admin' }],
    ltv: 9400, riskScore: 'low',
  },
  {
    _id: 'c004', firstName: 'David', lastName: 'Kim',
    email: 'dkim@gmail.com', phone: '+1 (206) 555-0404',
    role: 'buyer', isActive: false, emailVerified: true, isBanned: false,
    totalOrders: 3, totalSpent: 289.40, avgOrderValue: 96.5, lastOrderAt: d(92),
    createdAt: d(310), addresses: [{ label: 'Home', street: '77 Pine St', city: 'Seattle', state: 'WA', zip: '98101', country: 'US', isDefault: true }],
    savedCards: 1, wishlistCount: 2, reviewCount: 1,
    tags: ['At Risk', 'Inactive'],
    notes: [{ _id: 'n3', text: 'Last seen 3 months ago. Send win-back email.', createdAt: d(5), author: 'Admin' }],
    ltv: 500, riskScore: 'medium',
  },
  {
    _id: 'c005', firstName: 'Jessica', lastName: 'Williams',
    email: 'jwilliams@outlook.com', phone: '+1 (512) 555-0505',
    role: 'buyer', isActive: true, emailVerified: false, isBanned: false,
    totalOrders: 1, totalSpent: 86.38, avgOrderValue: 86.4, lastOrderAt: d(3),
    createdAt: d(8), addresses: [{ label: 'Home', street: '654 Birch Lane', city: 'Austin', state: 'TX', zip: '78701', country: 'US', isDefault: true }],
    savedCards: 0, wishlistCount: 5, reviewCount: 0,
    tags: ['New', 'Unverified'],
    notes: [],
    ltv: 86, riskScore: 'medium',
  },
  {
    _id: 'c006', firstName: 'Robert', lastName: 'Nguyen',
    email: 'rnguyen@yahoo.com', phone: '+1 (305) 555-0606',
    role: 'buyer', isActive: true, emailVerified: true, isBanned: true,
    banReason: 'Multiple chargeback attempts (3x within 60 days)',
    totalOrders: 4, totalSpent: 0, avgOrderValue: 0, lastOrderAt: d(22),
    createdAt: d(90), addresses: [{ label: 'Home', street: '32 Ocean Dr', city: 'Miami', state: 'FL', zip: '33101', country: 'US', isDefault: true }],
    savedCards: 0, wishlistCount: 0, reviewCount: 0,
    tags: ['Banned', 'Fraudulent'],
    notes: [{ _id: 'n4', text: 'BANNED: 3 chargeback disputes. IP flagged: 192.168.1.44. Do not reinstate without review.', createdAt: d(18), author: 'Admin' }],
    ltv: 0, riskScore: 'high',
  },
  {
    _id: 'c007', firstName: 'Amanda', lastName: 'Foster',
    email: 'afoster@icloud.com', phone: '+1 (720) 555-0707',
    role: 'buyer', isActive: true, emailVerified: true, isBanned: false,
    totalOrders: 14, totalSpent: 1820.60, avgOrderValue: 130.0, lastOrderAt: d(7),
    createdAt: d(480), addresses: [{ label: 'Home', street: '89 Spruce Ave', city: 'Denver', state: 'CO', zip: '80201', country: 'US', isDefault: true }],
    savedCards: 2, wishlistCount: 9, reviewCount: 6,
    tags: ['Repeat Buyer', 'VIP'],
    notes: [],
    ltv: 2900, riskScore: 'low',
  },
  {
    _id: 'c008', firstName: 'Thomas', lastName: 'Wright',
    email: 'twright@hotmail.com', phone: '+1 (617) 555-0808',
    role: 'buyer', isActive: true, emailVerified: true, isBanned: false,
    totalOrders: 6, totalSpent: 534.70, avgOrderValue: 89.1, lastOrderAt: d(13),
    createdAt: d(170), addresses: [{ label: 'Home', street: '14 Beacon St', city: 'Boston', state: 'MA', zip: '02101', country: 'US', isDefault: true }],
    savedCards: 1, wishlistCount: 3, reviewCount: 2,
    tags: ['Active'],
    notes: [],
    ltv: 900, riskScore: 'low',
  },
  {
    _id: 'c009', firstName: 'Aisha', lastName: 'Patel',
    email: 'apatel@proton.me', phone: '+1 (713) 555-0909',
    role: 'buyer', isActive: false, emailVerified: false, isBanned: false,
    totalOrders: 0, totalSpent: 0, avgOrderValue: 0, lastOrderAt: null,
    createdAt: d(6), addresses: [],
    savedCards: 0, wishlistCount: 2, reviewCount: 0,
    tags: ['New', 'Unverified', 'No Orders'],
    notes: [],
    ltv: 0, riskScore: 'medium',
  },
  {
    _id: 'c010', firstName: 'Carlos', lastName: 'Mendez',
    email: 'cmendez@corp.com', phone: '+1 (787) 555-1010',
    role: 'buyer', isActive: true, emailVerified: true, isBanned: false,
    totalOrders: 18, totalSpent: 2280.90, avgOrderValue: 126.7, lastOrderAt: d(5),
    createdAt: d(350), addresses: [{ label: 'Home', street: '55 Calle Sol', city: 'San Juan', state: 'PR', zip: '00901', country: 'PR', isDefault: true }],
    savedCards: 2, wishlistCount: 11, reviewCount: 7,
    tags: ['Repeat Buyer', 'VIP'],
    notes: [],
    ltv: 3600, riskScore: 'low',
  },
  {
    _id: 'c011', firstName: 'Lily', lastName: 'Zhang',
    email: 'lzhang@gmail.com', phone: '+1 (929) 555-1111',
    role: 'buyer', isActive: true, emailVerified: true, isBanned: false,
    totalOrders: 42, totalSpent: 7340.20, avgOrderValue: 174.8, lastOrderAt: d(0),
    createdAt: d(900), addresses: [{ label: 'Home', street: '200 West End Ave', city: 'New York', state: 'NY', zip: '10023', country: 'US', isDefault: true }],
    savedCards: 4, wishlistCount: 30, reviewCount: 21,
    tags: ['VIP', 'Top Spender', 'Repeat Buyer', 'Brand Ambassador'],
    notes: [{ _id: 'n5', text: 'Our highest-value customer. Invited to VIP beta program. Personal account manager: assigned.', createdAt: d(60), author: 'Admin' }],
    ltv: 14000, riskScore: 'low',
  },
  {
    _id: 'c012', firstName: 'James', lastName: 'O\'Brien',
    email: 'jobrien@fastmail.com', phone: '+1 (773) 555-1212',
    role: 'buyer', isActive: true, emailVerified: true, isBanned: false,
    totalOrders: 8, totalSpent: 760.15, avgOrderValue: 95.0, lastOrderAt: d(19),
    createdAt: d(260), addresses: [{ label: 'Home', street: '1400 N Lake Shore Dr', city: 'Chicago', state: 'IL', zip: '60610', country: 'US', isDefault: true }],
    savedCards: 1, wishlistCount: 6, reviewCount: 3,
    tags: ['Active'],
    notes: [],
    ltv: 1200, riskScore: 'low',
  },
];

// Dummy orders for a customer's order history tab
export const DUMMY_CUSTOMER_ORDERS = [
  { _id: 'o1', orderNumber: 'ORD-10421', status: 'delivered', totalAmount: 258.36, itemCount: 2, placedAt: new Date(Date.now() - 86400000 * 5).toISOString() },
  { _id: 'o2', orderNumber: 'ORD-10389', status: 'delivered', totalAmount: 189.99, itemCount: 1, placedAt: new Date(Date.now() - 86400000 * 30).toISOString() },
  { _id: 'o3', orderNumber: 'ORD-10312', status: 'refunded',  totalAmount: 64.50,  itemCount: 1, placedAt: new Date(Date.now() - 86400000 * 60).toISOString() },
  { _id: 'o4', orderNumber: 'ORD-10280', status: 'delivered', totalAmount: 344.00, itemCount: 3, placedAt: new Date(Date.now() - 86400000 * 90).toISOString() },
  { _id: 'o5', orderNumber: 'ORD-10201', status: 'delivered', totalAmount: 112.50, itemCount: 2, placedAt: new Date(Date.now() - 86400000 * 120).toISOString() },
];

// Dummy activity feed
export const makeDummyActivity = (customer) => [
  { type: 'order',   icon: '🛍️', text: `Placed order #ORD-10421 — SAR 258.36`,              time: new Date(Date.now() - 86400000 * 5).toISOString() },
  { type: 'review',  icon: '⭐', text: `Left 5-star review on "Merino Wool Blanket"`,     time: new Date(Date.now() - 86400000 * 8).toISOString() },
  { type: 'wishlist',icon: '❤️', text: `Added "Mechanical Keyboard TKL" to wishlist`,     time: new Date(Date.now() - 86400000 * 10).toISOString() },
  { type: 'order',   icon: '🛍️', text: `Placed order #ORD-10389 — SAR 189.99`,              time: new Date(Date.now() - 86400000 * 30).toISOString() },
  { type: 'coupon',  icon: '🎟️', text: `Applied coupon SAVE20 (saved SAR 38.00)`,           time: new Date(Date.now() - 86400000 * 32).toISOString() },
  { type: 'login',   icon: '🔐', text: `Logged in from Chrome / macOS (New York, US)`,   time: new Date(Date.now() - 86400000 * 35).toISOString() },
  { type: 'review',  icon: '⭐', text: `Left 4-star review on "Ceramic Coffee Dripper"`, time: new Date(Date.now() - 86400000 * 50).toISOString() },
  { type: 'order',   icon: '🛍️', text: `Placed order #ORD-10312 — SAR 64.50 (refunded)`,   time: new Date(Date.now() - 86400000 * 60).toISOString() },
  { type: 'email',   icon: '📧', text: `Email address verified`,                          time: new Date(Date.now() - 86400000 * 100).toISOString() },
  { type: 'signup',  icon: '👤', text: `Account created`,                                 time: new Date(customer.createdAt).toISOString() },
];
