// 📁 PATH: src/components/admin/shipping-zones/_dummyData.js
// Bangladesh-centric shipping zones with realistic rates (SAR)

const past = (d) => new Date(Date.now() - d * 86400000).toISOString();

export const BD_DIVISIONS = [
  'Dhaka', 'Chattogram', 'Khulna', 'Rajshahi',
  'Sylhet', 'Barishal', 'Rangpur', 'Mymensingh',
];

export const DUMMY_ZONES = [
  {
    _id: 'z01',
    name: 'Dhaka City (Inside)',
    code: 'DHK-IN',
    type: 'city',
    regions: ['Dhanmondi', 'Gulshan', 'Banani', 'Mirpur', 'Mohammadpur', 'Uttara', 'Bashundhara', 'Motijheel', 'Old Dhaka'],
    division: 'Dhaka',
    baseRate: 60,
    perKgRate: 20,
    freeShippingThreshold: 1500,
    estimatedDays: { min: 1, max: 2 },
    codAvailable: true,
    codCharge: 15,
    isActive: true,
    priority: 1,
    couriersAllowed: ['Pathao', 'Steadfast', 'RedX', 'Paperfly'],
    orders30d: 4280,
    createdAt: past(180),
  },
  {
    _id: 'z02',
    name: 'Dhaka Suburb',
    code: 'DHK-OUT',
    type: 'district',
    regions: ['Savar', 'Keraniganj', 'Dohar', 'Nawabganj', 'Tongi', 'Gazipur', 'Narayanganj'],
    division: 'Dhaka',
    baseRate: 100,
    perKgRate: 25,
    freeShippingThreshold: 2000,
    estimatedDays: { min: 2, max: 3 },
    codAvailable: true,
    codCharge: 20,
    isActive: true,
    priority: 2,
    couriersAllowed: ['Pathao', 'Steadfast', 'RedX', 'Paperfly', 'Sundarban'],
    orders30d: 1840,
    createdAt: past(180),
  },
  {
    _id: 'z03',
    name: 'Chattogram Metropolitan',
    code: 'CTG-METRO',
    type: 'city',
    regions: ['Agrabad', 'GEC', 'Nasirabad', 'Halishahar', 'Pahartali', 'Bayazid', 'Chandgaon'],
    division: 'Chattogram',
    baseRate: 130,
    perKgRate: 30,
    freeShippingThreshold: 2500,
    estimatedDays: { min: 2, max: 3 },
    codAvailable: true,
    codCharge: 25,
    isActive: true,
    priority: 3,
    couriersAllowed: ['Steadfast', 'RedX', 'Sundarban', 'SA Paribahan'],
    orders30d: 2110,
    createdAt: past(180),
  },
  {
    _id: 'z04',
    name: 'Sylhet Division',
    code: 'SYL-ALL',
    type: 'division',
    regions: ['Sylhet Sadar', 'Moulvibazar', 'Habiganj', 'Sunamganj'],
    division: 'Sylhet',
    baseRate: 150,
    perKgRate: 35,
    freeShippingThreshold: 3000,
    estimatedDays: { min: 3, max: 5 },
    codAvailable: true,
    codCharge: 30,
    isActive: true,
    priority: 4,
    couriersAllowed: ['Steadfast', 'Sundarban', 'SA Paribahan'],
    orders30d: 720,
    createdAt: past(150),
  },
  {
    _id: 'z05',
    name: 'Khulna & Jessore',
    code: 'KHL-WEST',
    type: 'division',
    regions: ['Khulna Sadar', 'Jessore', 'Satkhira', 'Bagerhat', 'Magura'],
    division: 'Khulna',
    baseRate: 140,
    perKgRate: 35,
    freeShippingThreshold: 2500,
    estimatedDays: { min: 3, max: 5 },
    codAvailable: true,
    codCharge: 30,
    isActive: true,
    priority: 5,
    couriersAllowed: ['Sundarban', 'SA Paribahan', 'Steadfast'],
    orders30d: 560,
    createdAt: past(120),
  },
  {
    _id: 'z06',
    name: 'Rajshahi & North',
    code: 'RAJ-NORTH',
    type: 'division',
    regions: ['Rajshahi Sadar', 'Bogura', 'Pabna', 'Naogaon', 'Natore'],
    division: 'Rajshahi',
    baseRate: 140,
    perKgRate: 35,
    freeShippingThreshold: 2500,
    estimatedDays: { min: 3, max: 4 },
    codAvailable: true,
    codCharge: 30,
    isActive: true,
    priority: 6,
    couriersAllowed: ['Sundarban', 'SA Paribahan'],
    orders30d: 480,
    createdAt: past(120),
  },
  {
    _id: 'z07',
    name: 'Rangpur Division',
    code: 'RNG-ALL',
    type: 'division',
    regions: ['Rangpur Sadar', 'Dinajpur', 'Thakurgaon', 'Kurigram', 'Gaibandha'],
    division: 'Rangpur',
    baseRate: 160,
    perKgRate: 40,
    freeShippingThreshold: 3000,
    estimatedDays: { min: 4, max: 6 },
    codAvailable: true,
    codCharge: 35,
    isActive: true,
    priority: 7,
    couriersAllowed: ['Sundarban', 'SA Paribahan'],
    orders30d: 310,
    createdAt: past(100),
  },
  {
    _id: 'z08',
    name: 'Barishal Riverine',
    code: 'BAR-ALL',
    type: 'division',
    regions: ['Barishal Sadar', 'Patuakhali', 'Bhola', 'Pirojpur', 'Jhalokati'],
    division: 'Barishal',
    baseRate: 170,
    perKgRate: 40,
    freeShippingThreshold: 3000,
    estimatedDays: { min: 4, max: 6 },
    codAvailable: true,
    codCharge: 35,
    isActive: true,
    priority: 8,
    couriersAllowed: ['Sundarban', 'SA Paribahan'],
    orders30d: 240,
    createdAt: past(100),
  },
  {
    _id: 'z09',
    name: 'Hill Tracts (Remote)',
    code: 'HILL-REM',
    type: 'remote',
    regions: ['Rangamati', 'Bandarban', 'Khagrachhari'],
    division: 'Chattogram',
    baseRate: 220,
    perKgRate: 55,
    freeShippingThreshold: 5000,
    estimatedDays: { min: 5, max: 8 },
    codAvailable: false,
    codCharge: 0,
    isActive: true,
    priority: 9,
    couriersAllowed: ['Sundarban'],
    orders30d: 65,
    createdAt: past(60),
  },
  {
    _id: 'z10',
    name: 'Cox\'s Bazar Tourist',
    code: 'COX-TOUR',
    type: 'district',
    regions: ['Cox\'s Bazar Sadar', 'Teknaf', 'Ukhia'],
    division: 'Chattogram',
    baseRate: 180,
    perKgRate: 45,
    freeShippingThreshold: 3500,
    estimatedDays: { min: 4, max: 6 },
    codAvailable: true,
    codCharge: 35,
    isActive: false,
    priority: 10,
    couriersAllowed: ['Sundarban', 'Steadfast'],
    orders30d: 0,
    createdAt: past(40),
  },
];

export const ZONE_TYPES = [
  { value: 'city',     label: '🏙️  City',     cls: 'bg-violet-500/10 text-violet-400 border-violet-500/20' },
  { value: 'district', label: '📍 District', cls: 'bg-sky-500/10 text-sky-400 border-sky-500/20' },
  { value: 'division', label: '🗺️  Division', cls: 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20' },
  { value: 'remote',   label: '⛰️  Remote',   cls: 'bg-amber-500/10 text-amber-400 border-amber-500/20' },
];
