// 📁 PATH: src/components/admin/tracking/_dummyData.js
// Real-time shipment tracking dummy data (Amazon/Daraz-style)

const past = (h) => new Date(Date.now() - h * 3600000).toISOString();
const future = (h) => new Date(Date.now() + h * 3600000).toISOString();

// Standard tracking statuses (lifecycle)
export const TRACKING_STATUSES = {
  pending:        { label: 'Pending Pickup',     order: 1, cls: 'bg-slate-700/30 text-slate-400 border-slate-700/50', dot: 'bg-slate-400', icon: '📋' },
  picked_up:      { label: 'Picked Up',          order: 2, cls: 'bg-sky-500/10 text-sky-400 border-sky-500/20',       dot: 'bg-sky-400',  icon: '📦' },
  in_transit:     { label: 'In Transit',         order: 3, cls: 'bg-violet-500/10 text-violet-400 border-violet-500/20', dot: 'bg-violet-400', icon: '🚛' },
  at_hub:         { label: 'At Sorting Hub',     order: 4, cls: 'bg-indigo-500/10 text-indigo-400 border-indigo-500/20', dot: 'bg-indigo-400', icon: '🏭' },
  out_for_delivery:{ label: 'Out for Delivery',  order: 5, cls: 'bg-amber-500/10 text-amber-400 border-amber-500/20', dot: 'bg-amber-400', icon: '🛵' },
  delivered:      { label: 'Delivered',          order: 6, cls: 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20', dot: 'bg-emerald-400', icon: '✅' },
  failed_attempt: { label: 'Failed Attempt',     order: 5, cls: 'bg-orange-500/10 text-orange-400 border-orange-500/20', dot: 'bg-orange-400', icon: '⚠️' },
  returned:       { label: 'Returned',           order: 7, cls: 'bg-red-500/10 text-red-400 border-red-500/20', dot: 'bg-red-400', icon: '↩️' },
  cancelled:      { label: 'Cancelled',          order: 0, cls: 'bg-slate-700/30 text-slate-500 border-slate-700/50', dot: 'bg-slate-500', icon: '✕' },
};

export const PRIORITIES = {
  high:   { label: '🔴 High',   cls: 'bg-red-500/10 text-red-400 border-red-500/20' },
  medium: { label: '🟡 Medium', cls: 'bg-amber-500/10 text-amber-400 border-amber-500/20' },
  low:    { label: '🟢 Low',    cls: 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20' },
};

const buildEvents = (statuses, baseHoursAgo) => {
  let h = baseHoursAgo;
  return statuses.map((s, i) => {
    const ev = {
      status: s.status,
      location: s.location,
      note: s.note,
      timestamp: past(h),
      operator: s.operator || 'System',
    };
    h -= s.hoursLater || 6;
    return ev;
  }).reverse();
};

export const DUMMY_SHIPMENTS = [
  {
    _id: 's01',
    trackingNumber: 'PTH-2025-118402',
    orderId: 'ORD-58392',
    courier: 'Pathao Courier',
    courierCode: 'PATHAO',
    status: 'out_for_delivery',
    priority: 'high',
    customer: { name: 'Tanvir Rahman', phone: '+8801712345678', address: 'House 12, Road 7, Dhanmondi, Dhaka 1209' },
    items: [{ name: 'Samsung Galaxy A55 5G', qty: 1, sku: 'SM-A556-256' }],
    weight: 0.45, value: 48500, codAmount: 48500,
    pickupLocation: 'Warehouse 1, Tejgaon, Dhaka',
    currentLocation: 'Dhanmondi Hub',
    estimatedDelivery: future(4),
    deliveryAttempts: 0,
    isCod: true,
    createdAt: past(28),
    events: buildEvents([
      { status: 'pending',          location: 'Order received',          note: 'Order placed by customer', hoursLater: 2 },
      { status: 'picked_up',        location: 'Tejgaon Warehouse',       note: 'Picked up by rider Rakib', operator: 'Rakib (P-204)', hoursLater: 6 },
      { status: 'in_transit',       location: 'Tejgaon → Dhanmondi',     note: 'Bike on route', operator: 'Rakib (P-204)', hoursLater: 4 },
      { status: 'at_hub',           location: 'Dhanmondi Hub',           note: 'Sorted for last-mile', hoursLater: 2 },
      { status: 'out_for_delivery', location: 'Dhanmondi Hub',           note: 'Out with rider for final delivery', operator: 'Karim (P-118)' },
    ], 28),
  },
  {
    _id: 's02',
    trackingNumber: 'STD-2025-29481',
    orderId: 'ORD-58388',
    courier: 'Steadfast Courier',
    courierCode: 'STEADFAST',
    status: 'delivered',
    priority: 'medium',
    customer: { name: 'Farzana Akter', phone: '+8801812345678', address: 'Flat 4B, Lalmatia Block C, Dhaka' },
    items: [
      { name: 'Logitech MX Master 3S', qty: 1, sku: 'LG-MX3S-BLK' },
      { name: 'Mouse Pad XL', qty: 1, sku: 'MP-XL-001' },
    ],
    weight: 0.9, value: 14500, codAmount: 0,
    pickupLocation: 'Warehouse 1, Tejgaon',
    currentLocation: 'Delivered',
    estimatedDelivery: past(2),
    deliveredAt: past(2),
    deliveryAttempts: 1,
    isCod: false,
    signature: 'F. Akter',
    createdAt: past(52),
    events: buildEvents([
      { status: 'pending',          location: 'Order received',  hoursLater: 1 },
      { status: 'picked_up',        location: 'Tejgaon WH',      operator: 'Steadfast Rider-9', hoursLater: 8 },
      { status: 'in_transit',       location: 'WH → Central Hub',hoursLater: 6 },
      { status: 'at_hub',           location: 'Central Hub, Mohakhali', hoursLater: 12 },
      { status: 'out_for_delivery', location: 'Lalmatia Branch', operator: 'Sumon (SF-44)', hoursLater: 3 },
      { status: 'delivered',        location: 'Customer Address',note: 'Delivered to F. Akter', operator: 'Sumon (SF-44)' },
    ], 52),
  },
  {
    _id: 's03',
    trackingNumber: 'RDX-2025-77321',
    orderId: 'ORD-58371',
    courier: 'RedX',
    courierCode: 'REDX',
    status: 'in_transit',
    priority: 'medium',
    customer: { name: 'Mahmud Hossain', phone: '+8801912345678', address: 'Plot 22, GEC Circle, Chattogram' },
    items: [{ name: 'Sony WH-1000XM5 Headphones', qty: 1, sku: 'SNY-WH1KXM5' }],
    weight: 0.7, value: 39800, codAmount: 39800,
    pickupLocation: 'Warehouse 2, Mirpur',
    currentLocation: 'Cumilla Transit Point',
    estimatedDelivery: future(30),
    deliveryAttempts: 0,
    isCod: true,
    createdAt: past(36),
    events: buildEvents([
      { status: 'pending',    location: 'Order received', hoursLater: 4 },
      { status: 'picked_up',  location: 'Mirpur WH', operator: 'RedX P-12', hoursLater: 10 },
      { status: 'at_hub',     location: 'Dhaka Central Hub', hoursLater: 8 },
      { status: 'in_transit', location: 'Dhaka → Chattogram (Cumilla)', operator: 'Truck CTG-09', note: 'Long-haul truck' },
    ], 36),
  },
  {
    _id: 's04',
    trackingNumber: 'PTH-2025-118395',
    orderId: 'ORD-58302',
    courier: 'Pathao Courier',
    courierCode: 'PATHAO',
    status: 'failed_attempt',
    priority: 'high',
    customer: { name: 'Nusrat Jahan', phone: '+8801512345678', address: 'House 5, Banani Road 11, Dhaka' },
    items: [{ name: 'Apple Watch Series 10', qty: 1, sku: 'APL-WS10-45' }],
    weight: 0.3, value: 68500, codAmount: 68500,
    pickupLocation: 'Warehouse 1, Tejgaon',
    currentLocation: 'Banani Hub (Re-attempt)',
    estimatedDelivery: future(20),
    deliveryAttempts: 1,
    isCod: true,
    failureReason: 'Customer not available — phone switched off',
    createdAt: past(48),
    events: buildEvents([
      { status: 'pending',           location: 'Order received',  hoursLater: 1 },
      { status: 'picked_up',         location: 'Tejgaon WH',      operator: 'P-204', hoursLater: 5 },
      { status: 'in_transit',        location: 'WH → Banani',     hoursLater: 6 },
      { status: 'at_hub',            location: 'Banani Hub',      hoursLater: 10 },
      { status: 'out_for_delivery',  location: 'Banani Hub',      operator: 'P-77', hoursLater: 4 },
      { status: 'failed_attempt',    location: 'Customer doorstep', note: 'Customer not reachable. Re-attempt tomorrow.', operator: 'P-77' },
    ], 48),
  },
  {
    _id: 's05',
    trackingNumber: 'SDB-2025-09128',
    orderId: 'ORD-58277',
    courier: 'Sundarban Courier',
    courierCode: 'SUNDARBAN',
    status: 'picked_up',
    priority: 'low',
    customer: { name: 'Rashedul Karim', phone: '+8801612345678', address: 'Holding 88, Kazipara, Rangpur Sadar' },
    items: [
      { name: 'Philips Air Fryer XL', qty: 1, sku: 'PHL-AF-XL' },
      { name: 'Kitchen Tool Set', qty: 2, sku: 'KT-SET-01' },
    ],
    weight: 3.2, value: 18900, codAmount: 18900,
    pickupLocation: 'Warehouse 3, Savar',
    currentLocation: 'Sundarban Pickup Centre — Savar',
    estimatedDelivery: future(96),
    deliveryAttempts: 0,
    isCod: true,
    createdAt: past(6),
    events: buildEvents([
      { status: 'pending',   location: 'Order received', hoursLater: 1 },
      { status: 'picked_up', location: 'Sundarban Pickup, Savar', operator: 'Counter Desk', note: 'Parcel received at counter' },
    ], 6),
  },
  {
    _id: 's06',
    trackingNumber: 'STD-2025-29402',
    orderId: 'ORD-58241',
    courier: 'Steadfast Courier',
    courierCode: 'STEADFAST',
    status: 'returned',
    priority: 'medium',
    customer: { name: 'Sabbir Ahmed', phone: '+8801714111222', address: 'Road 3, Mohammadpur, Dhaka' },
    items: [{ name: 'Generic USB-C Cable 2m', qty: 5, sku: 'USB-C-2M' }],
    weight: 0.4, value: 1450, codAmount: 1450,
    pickupLocation: 'Warehouse 1, Tejgaon',
    currentLocation: 'Returned to Warehouse 1',
    estimatedDelivery: past(48),
    deliveryAttempts: 3,
    isCod: true,
    failureReason: 'Customer refused — wrong product expectation',
    createdAt: past(120),
    events: buildEvents([
      { status: 'pending',           location: 'Order',                hoursLater: 2 },
      { status: 'picked_up',         location: 'Tejgaon WH',           hoursLater: 12 },
      { status: 'in_transit',        location: 'WH → Mohammadpur Hub', hoursLater: 8 },
      { status: 'out_for_delivery',  location: 'Mohammadpur Hub',      hoursLater: 6 },
      { status: 'failed_attempt',    location: 'Customer doorstep',    note: 'Attempt 1 — refused', hoursLater: 24 },
      { status: 'out_for_delivery',  location: 'Mohammadpur Hub',      hoursLater: 6 },
      { status: 'failed_attempt',    location: 'Customer doorstep',    note: 'Attempt 2 — refused', hoursLater: 24 },
      { status: 'returned',          location: 'Back to Warehouse 1',  note: 'Returned after 3 failed attempts' },
    ], 120),
  },
  {
    _id: 's07',
    trackingNumber: 'PTH-2025-118450',
    orderId: 'ORD-58410',
    courier: 'Pathao Courier',
    courierCode: 'PATHAO',
    status: 'pending',
    priority: 'medium',
    customer: { name: 'Maliha Khan', phone: '+8801912333444', address: 'House 19, Uttara Sector 7, Dhaka' },
    items: [{ name: 'Xiaomi Mi Band 9', qty: 1, sku: 'XM-MB9' }],
    weight: 0.2, value: 3200, codAmount: 0,
    pickupLocation: 'Warehouse 1, Tejgaon',
    currentLocation: 'Awaiting pickup',
    estimatedDelivery: future(48),
    deliveryAttempts: 0,
    isCod: false,
    createdAt: past(1),
    events: buildEvents([
      { status: 'pending', location: 'Order received', note: 'Awaiting courier pickup' },
    ], 1),
  },
  {
    _id: 's08',
    trackingNumber: 'PFL-2025-44218',
    orderId: 'ORD-58198',
    courier: 'Paperfly',
    courierCode: 'PAPERFLY',
    status: 'delivered',
    priority: 'low',
    customer: { name: 'Imran Hossain', phone: '+8801614789632', address: 'Block D, Bashundhara R/A, Dhaka' },
    items: [{ name: 'IKEA-style Desk Lamp', qty: 1, sku: 'LMP-DSK-01' }],
    weight: 1.1, value: 2800, codAmount: 2800,
    pickupLocation: 'Warehouse 2, Mirpur',
    currentLocation: 'Delivered',
    estimatedDelivery: past(20),
    deliveredAt: past(18),
    deliveryAttempts: 1,
    isCod: true,
    signature: 'I. Hossain',
    createdAt: past(72),
    events: buildEvents([
      { status: 'pending',          location: 'Order',           hoursLater: 3 },
      { status: 'picked_up',        location: 'Mirpur WH',       operator: 'PF-09', hoursLater: 10 },
      { status: 'at_hub',           location: 'Paperfly Hub',    hoursLater: 18 },
      { status: 'out_for_delivery', location: 'Bashundhara Hub', operator: 'PF-22', hoursLater: 5 },
      { status: 'delivered',        location: 'Customer Address',note: 'Cash collected SAR 2800' },
    ], 72),
  },
];
