// 📁 PATH: src/components/admin/couriers/_dummyData.js
// Bangladesh courier providers — realistic dummy data

const past = (d) => new Date(Date.now() - d * 86400000).toISOString();

export const DUMMY_COURIERS = [
  {
    _id: 'cr01',
    name: 'Pathao Courier',
    code: 'PATHAO',
    logo: '🛵',
    type: 'in_house',
    apiIntegrated: true,
    apiStatus: 'connected',
    contactPerson: 'Rakib Hasan',
    phone: '+8801711111111',
    email: 'support@pathao.com',
    website: 'https://merchant.pathao.com',
    coverageAreas: ['Dhaka', 'Chattogram', 'Sylhet'],
    serviceTypes: ['regular', 'same_day', 'express'],
    baseRate: 60,
    perKgRate: 20,
    codChargePercent: 1.0,
    pickupCharge: 0,
    insuranceAvailable: true,
    avgDeliveryHours: 36,
    successRate: 96.8,
    returnRate: 3.2,
    activeShipments: 1240,
    completedShipments: 18540,
    rating: 4.6,
    isActive: true,
    isPreferred: true,
    notes: 'Best for inside Dhaka same-day delivery.',
    createdAt: past(365),
  },
  {
    _id: 'cr02',
    name: 'Steadfast Courier',
    code: 'STEADFAST',
    logo: '⚡',
    type: 'third_party',
    apiIntegrated: true,
    apiStatus: 'connected',
    contactPerson: 'Mahmudul Hasan',
    phone: '+8801712222222',
    email: 'biz@steadfast.com.bd',
    website: 'https://steadfast.com.bd',
    coverageAreas: ['Dhaka', 'Chattogram', 'Khulna', 'Rajshahi', 'Sylhet', 'Barishal', 'Rangpur', 'Mymensingh'],
    serviceTypes: ['regular', 'express'],
    baseRate: 70,
    perKgRate: 25,
    codChargePercent: 1.0,
    pickupCharge: 0,
    insuranceAvailable: true,
    avgDeliveryHours: 48,
    successRate: 94.2,
    returnRate: 5.8,
    activeShipments: 2870,
    completedShipments: 42180,
    rating: 4.5,
    isActive: true,
    isPreferred: true,
    notes: 'Nationwide coverage with reliable API.',
    createdAt: past(400),
  },
  {
    _id: 'cr03',
    name: 'RedX',
    code: 'REDX',
    logo: '🔴',
    type: 'third_party',
    apiIntegrated: true,
    apiStatus: 'connected',
    contactPerson: 'Tanvir Ahmed',
    phone: '+8801713333333',
    email: 'support@redx.com.bd',
    website: 'https://redx.com.bd',
    coverageAreas: ['Dhaka', 'Chattogram', 'Sylhet', 'Khulna'],
    serviceTypes: ['regular', 'same_day'],
    baseRate: 65,
    perKgRate: 22,
    codChargePercent: 1.0,
    pickupCharge: 0,
    insuranceAvailable: false,
    avgDeliveryHours: 40,
    successRate: 93.5,
    returnRate: 6.5,
    activeShipments: 980,
    completedShipments: 12300,
    rating: 4.3,
    isActive: true,
    isPreferred: false,
    notes: 'Good for medium-volume daily pickups.',
    createdAt: past(280),
  },
  {
    _id: 'cr04',
    name: 'Paperfly',
    code: 'PAPERFLY',
    logo: '📦',
    type: 'third_party',
    apiIntegrated: true,
    apiStatus: 'connected',
    contactPerson: 'Shahriar Kabir',
    phone: '+8801714444444',
    email: 'support@paperfly.com.bd',
    website: 'https://paperfly.com.bd',
    coverageAreas: ['Dhaka', 'Chattogram', 'Khulna', 'Rajshahi', 'Sylhet'],
    serviceTypes: ['regular', 'express', 'fragile'],
    baseRate: 80,
    perKgRate: 28,
    codChargePercent: 1.2,
    pickupCharge: 30,
    insuranceAvailable: true,
    avgDeliveryHours: 60,
    successRate: 92.0,
    returnRate: 8.0,
    activeShipments: 540,
    completedShipments: 8920,
    rating: 4.1,
    isActive: true,
    isPreferred: false,
    notes: 'Specialized in fragile/electronics handling.',
    createdAt: past(220),
  },
  {
    _id: 'cr05',
    name: 'Sundarban Courier',
    code: 'SUNDARBAN',
    logo: '🌳',
    type: 'third_party',
    apiIntegrated: false,
    apiStatus: 'manual',
    contactPerson: 'Office Manager',
    phone: '+8802222333333',
    email: 'info@sundarbancourierltd.com',
    website: 'https://sundarbancourierltd.com',
    coverageAreas: ['Dhaka', 'Chattogram', 'Khulna', 'Rajshahi', 'Sylhet', 'Barishal', 'Rangpur', 'Mymensingh'],
    serviceTypes: ['regular'],
    baseRate: 100,
    perKgRate: 35,
    codChargePercent: 1.5,
    pickupCharge: 50,
    insuranceAvailable: false,
    avgDeliveryHours: 96,
    successRate: 88.5,
    returnRate: 11.5,
    activeShipments: 320,
    completedShipments: 5640,
    rating: 3.8,
    isActive: true,
    isPreferred: false,
    notes: 'Best reach for remote areas (Hill Tracts).',
    createdAt: past(500),
  },
  {
    _id: 'cr06',
    name: 'SA Paribahan',
    code: 'SA',
    logo: '🚚',
    type: 'third_party',
    apiIntegrated: false,
    apiStatus: 'manual',
    contactPerson: 'Counter Desk',
    phone: '+8801715555555',
    email: 'info@saparibahan.com',
    website: 'https://saparibahan.com',
    coverageAreas: ['Dhaka', 'Chattogram', 'Khulna', 'Rajshahi', 'Sylhet', 'Barishal', 'Rangpur'],
    serviceTypes: ['regular', 'heavy'],
    baseRate: 90,
    perKgRate: 30,
    codChargePercent: 1.2,
    pickupCharge: 40,
    insuranceAvailable: false,
    avgDeliveryHours: 72,
    successRate: 90.0,
    returnRate: 10.0,
    activeShipments: 180,
    completedShipments: 3210,
    rating: 4.0,
    isActive: true,
    isPreferred: false,
    notes: 'Good for heavy/oversized parcels.',
    createdAt: past(450),
  },
  {
    _id: 'cr07',
    name: 'eCourier',
    code: 'ECOURIER',
    logo: '💼',
    type: 'third_party',
    apiIntegrated: true,
    apiStatus: 'disconnected',
    contactPerson: 'Sales Team',
    phone: '+8801716666666',
    email: 'sales@ecourier.com.bd',
    website: 'https://ecourier.com.bd',
    coverageAreas: ['Dhaka', 'Chattogram'],
    serviceTypes: ['regular', 'express'],
    baseRate: 75,
    perKgRate: 28,
    codChargePercent: 1.0,
    pickupCharge: 0,
    insuranceAvailable: true,
    avgDeliveryHours: 48,
    successRate: 91.0,
    returnRate: 9.0,
    activeShipments: 0,
    completedShipments: 2480,
    rating: 4.0,
    isActive: false,
    isPreferred: false,
    notes: 'API token expired — needs reconnection.',
    createdAt: past(200),
  },
];

export const COURIER_TYPES = [
  { value: 'in_house',     label: '🏢 In-House',     cls: 'bg-violet-500/10 text-violet-400 border-violet-500/20' },
  { value: 'third_party',  label: '🤝 Third Party',  cls: 'bg-sky-500/10 text-sky-400 border-sky-500/20' },
];

export const API_STATUS = {
  connected:    { label: 'Connected',    cls: 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20', dot: 'bg-emerald-400' },
  disconnected: { label: 'Disconnected', cls: 'bg-red-500/10 text-red-400 border-red-500/20', dot: 'bg-red-400' },
  manual:       { label: 'Manual Entry', cls: 'bg-slate-700/30 text-slate-400 border-slate-700/50', dot: 'bg-slate-500' },
};

export const SERVICE_TYPES = ['regular', 'express', 'same_day', 'fragile', 'heavy'];
