// 📁 PATH: src/components/admin/attributes/_dummyData.js
// ⚠️  DEV ONLY — backend ready হলে import সরিয়ে দাও

export const ATTRIBUTE_TYPES = [
  { value: 'select',    label: 'Dropdown (Select)',    icon: '▾',  desc: 'Single value from a list' },
  { value: 'multiselect', label: 'Multi-Select',       icon: '☑',  desc: 'Multiple values from a list' },
  { value: 'color',     label: 'Color Swatch',         icon: '🎨', desc: 'Visual color picker' },
  { value: 'boolean',   label: 'Yes / No',             icon: '◉',  desc: 'True or false toggle' },
  { value: 'text',      label: 'Text Input',           icon: 'T',  desc: 'Free-form text' },
  { value: 'number',    label: 'Number',               icon: '#',  desc: 'Numeric value' },
];

export const DUMMY_ATTRIBUTES = [
  {
    _id: 'attr_01',
    name: 'Color',
    slug: 'color',
    type: 'color',
    isRequired: false,
    isFilterable: true,
    isVariant: true,
    isActive: true,
    sortOrder: 1,
    usedInProducts: 84,
    values: [
      { _id: 'v01', label: 'Black',       value: '#000000', sortOrder: 1, isActive: true },
      { _id: 'v02', label: 'White',       value: '#FFFFFF', sortOrder: 2, isActive: true },
      { _id: 'v03', label: 'Navy Blue',   value: '#1B3A6B', sortOrder: 3, isActive: true },
      { _id: 'v04', label: 'Forest Green',value: '#2D5A27', sortOrder: 4, isActive: true },
      { _id: 'v05', label: 'Crimson Red', value: '#C41230', sortOrder: 5, isActive: true },
      { _id: 'v06', label: 'Sand',        value: '#C2B280', sortOrder: 6, isActive: false },
    ],
  },
  {
    _id: 'attr_02',
    name: 'Size',
    slug: 'size',
    type: 'select',
    isRequired: true,
    isFilterable: true,
    isVariant: true,
    isActive: true,
    sortOrder: 2,
    usedInProducts: 112,
    values: [
      { _id: 'v10', label: 'XS',   value: 'XS',   sortOrder: 1, isActive: true },
      { _id: 'v11', label: 'S',    value: 'S',    sortOrder: 2, isActive: true },
      { _id: 'v12', label: 'M',    value: 'M',    sortOrder: 3, isActive: true },
      { _id: 'v13', label: 'L',    value: 'L',    sortOrder: 4, isActive: true },
      { _id: 'v14', label: 'XL',   value: 'XL',   sortOrder: 5, isActive: true },
      { _id: 'v15', label: 'XXL',  value: 'XXL',  sortOrder: 6, isActive: true },
      { _id: 'v16', label: '3XL',  value: '3XL',  sortOrder: 7, isActive: false },
    ],
  },
  {
    _id: 'attr_03',
    name: 'Material',
    slug: 'material',
    type: 'select',
    isRequired: false,
    isFilterable: true,
    isVariant: false,
    isActive: true,
    sortOrder: 3,
    usedInProducts: 67,
    values: [
      { _id: 'v20', label: 'Cotton',          value: 'cotton',         sortOrder: 1, isActive: true },
      { _id: 'v21', label: 'Polyester',        value: 'polyester',      sortOrder: 2, isActive: true },
      { _id: 'v22', label: 'Wool',             value: 'wool',           sortOrder: 3, isActive: true },
      { _id: 'v23', label: 'Leather',          value: 'leather',        sortOrder: 4, isActive: true },
      { _id: 'v24', label: 'Stainless Steel',  value: 'stainless-steel',sortOrder: 5, isActive: true },
      { _id: 'v25', label: 'Bamboo',           value: 'bamboo',         sortOrder: 6, isActive: true },
    ],
  },
  {
    _id: 'attr_04',
    name: 'Storage Capacity',
    slug: 'storage-capacity',
    type: 'select',
    isRequired: false,
    isFilterable: true,
    isVariant: true,
    isActive: true,
    sortOrder: 4,
    usedInProducts: 28,
    values: [
      { _id: 'v30', label: '64 GB',  value: '64gb',  sortOrder: 1, isActive: true  },
      { _id: 'v31', label: '128 GB', value: '128gb', sortOrder: 2, isActive: true  },
      { _id: 'v32', label: '256 GB', value: '256gb', sortOrder: 3, isActive: true  },
      { _id: 'v33', label: '512 GB', value: '512gb', sortOrder: 4, isActive: true  },
      { _id: 'v34', label: '1 TB',   value: '1tb',   sortOrder: 5, isActive: false },
    ],
  },
  {
    _id: 'attr_05',
    name: 'Wireless',
    slug: 'wireless',
    type: 'boolean',
    isRequired: false,
    isFilterable: true,
    isVariant: false,
    isActive: true,
    sortOrder: 5,
    usedInProducts: 41,
    values: [],
  },
  {
    _id: 'attr_06',
    name: 'Weight (kg)',
    slug: 'weight-kg',
    type: 'number',
    isRequired: false,
    isFilterable: false,
    isVariant: false,
    isActive: true,
    sortOrder: 6,
    usedInProducts: 55,
    values: [],
  },
  {
    _id: 'attr_07',
    name: 'Connectivity',
    slug: 'connectivity',
    type: 'multiselect',
    isRequired: false,
    isFilterable: true,
    isVariant: false,
    isActive: true,
    sortOrder: 7,
    usedInProducts: 19,
    values: [
      { _id: 'v40', label: 'Bluetooth 5.0', value: 'bt5', sortOrder: 1, isActive: true },
      { _id: 'v41', label: 'USB-C',         value: 'usbc', sortOrder: 2, isActive: true },
      { _id: 'v42', label: 'Wi-Fi 6',       value: 'wifi6', sortOrder: 3, isActive: true },
      { _id: 'v43', label: 'NFC',           value: 'nfc',   sortOrder: 4, isActive: true },
    ],
  },
  {
    _id: 'attr_08',
    name: 'RAM',
    slug: 'ram',
    type: 'select',
    isRequired: false,
    isFilterable: true,
    isVariant: true,
    isActive: false,
    sortOrder: 8,
    usedInProducts: 0,
    values: [
      { _id: 'v50', label: '4 GB',  value: '4gb',  sortOrder: 1, isActive: true },
      { _id: 'v51', label: '8 GB',  value: '8gb',  sortOrder: 2, isActive: true },
      { _id: 'v52', label: '16 GB', value: '16gb', sortOrder: 3, isActive: true },
    ],
  },
];

export const DUMMY_STATS = {
  total:      DUMMY_ATTRIBUTES.length,
  active:     DUMMY_ATTRIBUTES.filter(a => a.isActive).length,
  inactive:   DUMMY_ATTRIBUTES.filter(a => !a.isActive).length,
  filterable: DUMMY_ATTRIBUTES.filter(a => a.isFilterable).length,
  variant:    DUMMY_ATTRIBUTES.filter(a => a.isVariant).length,
  totalValues: DUMMY_ATTRIBUTES.reduce((s, a) => s + a.values.length, 0),
};
